"use client";
/* eslint-disable @next/next/no-img-element */
import { ArrowUpRight, ArrowDown } from "@phosphor-icons/react";
import { formatMonth, SocialIcon } from "@/templates/shared";
import type { BoldData as PortfolioData } from "./schema";
import type { WorkspaceProfile } from "@/templates/definition";
import { boldDefinition } from "./definition";
export function BoldRenderer({ data }: { data: PortfolioData; workspaceProfile?: WorkspaceProfile }) {
 const {profile,experiences,skills,projects,contact,socials,theme,hiddenSections}=data; const hidden=(id:string)=>hiddenSections?.includes(id)??false; const v=boldDefinition.variants.find(x=>x.id===theme.variantId)||boldDefinition.variants[0]; const c=v.colors;
 return <div className="min-h-screen overflow-x-clip" style={{background:c.background,color:c.text}}><nav className="flex justify-between border-b-[3px] px-6 py-5 text-xs font-bold uppercase tracking-widest md:px-12" style={{borderColor:c.text}}><span>{profile.fullName||"BOLD"}<i style={{color:c.primary}}>.</i></span><a href="#contact">Work with me ↗</a></nav>
 {!hidden("profile")&&<header id="profile" className="border-b-[3px] px-6 py-20 md:px-12 md:py-32" style={{borderColor:c.text}}><p className="mb-8 text-xs font-bold uppercase tracking-[.3em]" style={{color:c.primary}}>Independent creative / {profile.location||"Worldwide"}</p><h1 className="max-w-[10ch] text-[clamp(4.5rem,15vw,13rem)] font-black uppercase leading-[.78] tracking-[-.09em]">{profile.fullName||"Your Name"}<span style={{color:c.primary}}>.</span></h1>{profile.headline&&<p className="mt-10 max-w-[26ch] text-2xl font-bold uppercase leading-tight md:text-4xl">{profile.headline}</p>}{profile.bio&&<p className="mt-8 max-w-[60ch] text-base leading-7" style={{color:c.textMuted}}>{profile.bio}</p>}<a href="#projects" className="mt-10 inline-flex items-center gap-3 border-[3px] px-5 py-3 text-xs font-bold uppercase tracking-widest transition-transform hover:-translate-y-1" style={{borderColor:c.text}}>See the work <ArrowDown/></a></header>}
 {projects.length>0&&!hidden("projects")&&<section id="projects" className="border-b-[3px] px-6 py-20 md:px-12 md:py-32" style={{borderColor:c.text}}><div className="mb-14 flex items-end justify-between"><h2 className="text-5xl font-black uppercase tracking-[-.07em] md:text-8xl">Work</h2><span className="text-xs font-bold uppercase tracking-widest">{String(projects.length).padStart(2,"0")} pieces</span></div><div className="grid gap-12 md:grid-cols-2">{projects.map((p,i)=><a key={i} href={p.link||undefined} className="group"><div className="relative aspect-[4/3] overflow-hidden" style={{background:c.surface}}>{p.imageUrl?<img src={p.imageUrl} alt={p.title} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"/>:<div className="flex h-full items-center justify-center text-[12rem] font-black" style={{color:c.primary}}>{p.title[0]}</div>}<span className="absolute left-4 top-4 bg-black px-3 py-2 text-xs font-bold text-white">0{i+1}</span></div><div className="mt-5 flex justify-between gap-4"><div><h3 className="text-2xl font-black uppercase tracking-tight">{p.title}</h3><p className="mt-2 max-w-md text-sm leading-6" style={{color:c.textMuted}}>{p.description}</p></div><ArrowUpRight size={26} style={{color:c.primary}}/></div></a>)}</div></section>}
 {experiences.length>0&&!hidden("experience")&&<section id="experience" className="border-b-[3px] px-6 py-20 md:px-12 md:py-32" style={{borderColor:c.text}}><h2 className="mb-14 text-5xl font-black uppercase tracking-[-.07em] md:text-8xl">Proof</h2>{experiences.map((e,i)=><article key={i} className="grid gap-4 border-t-2 py-7 md:grid-cols-[220px_1fr]" style={{borderColor:c.text}}><p className="text-xs font-bold uppercase tracking-widest" style={{color:c.textMuted}}>{formatMonth(e.startDate)} — {e.endDate?formatMonth(e.endDate):"Present"}</p><div><h3 className="text-2xl font-black uppercase">{e.role}</h3><p className="mt-1 font-bold uppercase" style={{color:c.primary}}>{e.company}</p>{e.description&&<p className="mt-4 max-w-2xl leading-7" style={{color:c.textMuted}}>{e.description}</p>}</div></article>)}</section>}
 {!hidden("skills")&&skills.length>0&&<section id="skills" className="border-b-[3px] px-6 py-20 md:px-12 md:py-32" style={{borderColor:c.text}}><h2 className="mb-10 text-5xl font-black uppercase tracking-[-.07em] md:text-8xl">Tools</h2><div className="flex flex-wrap gap-3">{skills.map(s=><span key={s} className="border-2 px-4 py-3 text-xs font-bold uppercase tracking-widest" style={{borderColor:c.text}}>{s}</span>)}</div></section>}
 {!hidden("contact")&&<footer id="contact" className="px-6 py-20 md:px-12 md:py-32" style={{background:c.text,color:c.background}}><h2 className="max-w-[10ch] text-6xl font-black uppercase leading-[.8] tracking-[-.08em] md:text-9xl" style={{color:c.primary}}>Make noise.</h2><div className="mt-16 flex flex-col gap-4 text-xl font-bold md:flex-row md:justify-between">{contact.email&&<a href={`mailto:${contact.email}`}>{contact.email}</a>}{contact.phone&&<span>{contact.phone}</span>}<div className="flex gap-5">{socials.map((s,i)=><a key={i} href={s.url}><SocialIcon platform={s.platform} size={24}/></a>)}</div></div></footer>}
 </div>;
}
export { BoldRenderer as BoldTemplate };
